# Generated by Django 5.2.1 on 2025-07-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id_lancamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('volume_agua', models.FloatField(default=750.0, verbose_name='Volume de Água (mL)')),
                ('angulo', models.FloatField(default=45.0, verbose_name='Ângulo (graus)')),
                ('pressao_lancamento', models.FloatField(default=53.03, verbose_name='Pressão Recomendada (PSI)')),
                ('distancia_alvo', models.FloatField(choices=[(10.0, '10 m'), (20.0, '20 m'), (30.0, '30 m')], default=10.0, verbose_name='Distância Alvo')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora completa do registro de telemetria')),
                ('aceleracao_x', models.FloatField(verbose_name='Aceleração X (g)')),
                ('aceleracao_y', models.FloatField(verbose_name='Aceleração Y (g)')),
                ('aceleracao_z', models.FloatField(verbose_name='Aceleração Z (g)')),
                ('vel_angular_x', models.FloatField(verbose_name='Giro X (°/s)')),
                ('vel_angular_y', models.FloatField(verbose_name='Giro Y (°/s)')),
                ('vel_angular_z', models.FloatField(verbose_name='Giro Z (°/s)')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('velocidade', models.FloatField(blank=True, null=True, verbose_name='Velocidade (km/h)')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='core.lancamento')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
