# Generated by Django 5.2.1 on 2025-07-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para lançamentos ativos', null=True),
        ),
    ]
