# Generated by Django 5.2.1 on 2025-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lancamento_angulo_lancamento_pressao_ajustada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='distancia_alvo',
            field=models.FloatField(choices=[(10.0, '10 m'), (20.0, '20 m'), (30.0, '30 m')], default=10.0),
        ),
    ]
