# Generated by Django 5.2.1 on 2025-05-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lancamento_distancia_alvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='angulo',
            field=models.FloatField(default=45.0, verbose_name='Ângulo (graus)'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='distancia_alvo',
            field=models.FloatField(choices=[(10.0, '10 m'), (20.0, '20 m'), (30.0, '30 m')], default=10.0, verbose_name='Distância Alvo'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='pressao_ajustada',
            field=models.FloatField(default=53.03, verbose_name='Pressão Ajustada (PSI)'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='pressao_recomendada',
            field=models.FloatField(default=53.03, verbose_name='Pressão Recomendada (PSI)'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='volume_agua',
            field=models.FloatField(default=750.0, verbose_name='Volume de Água (mL)'),
        ),
    ]
