# Generated by Django 5.2.1 on 2025-05-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lancamento_angulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='pressao_ajustada',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='pressao_recomendada',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='pressao_lancamento',
            field=models.FloatField(default=53.03, verbose_name='Pressão Recomendada (PSI)'),
        ),
    ]
