# Generated by Django 5.2.1 on 2025-06-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lancamento_pressao_ajustada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetria',
            name='bus_voltage',
        ),
        migrations.RemoveField(
            model_name='telemetria',
            name='current_mA',
        ),
        migrations.RemoveField(
            model_name='telemetria',
            name='power_mW',
        ),
        migrations.RemoveField(
            model_name='telemetria',
            name='shunt_voltage',
        ),
    ]
